###

# Requisição válida
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "arroz123",
    "marcadores": [
        {"tipo": "carro1"},
        {"cor": "branco"},
        {"modelo": "hb20"},
        {"arcondicionado": "sim"}
        {"direcao_hidraulica": "sim"}
        
    ],
    "valores": [
        {"latitude": -27.590059}, 
        {"longitude": -48.637676},
        {"preco": 600}
    ]
}

# arroz123,tipo=carro1,cor=branco,modelo=hb20,arcondicionado=sim,direcao_hidraulica=sim latitude=-27,longitude=-48,preco=600

###

# Requisição inválida: cabeçalho não menciona formato
POST http://localhost:5000/gravar
Accept: application/json

{
    "medida": "arroz123",
    "marcadores": [
        {"tipo": "carro1"},
        {"cor": "branco"},
        {"modelo": "hb20"},
        {"arcondicionado": "sim"}
        {"direcao_hidraulica": "sim"}
        
    ],
    "valores": [
        {"latitude": -27.590059}, 
        {"longitude": -48.637676},
        {"preco": 600}
    ]
}

###

# Requisição inválida: JSON com formato errado
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
   "medida": "arroz123",
    "marcadores": [
        {"tipo": "carro1"},
        {"cor": "branco"},
        {"modelo": "hb20"},
        {"arcondicionado": "sim"}
        {"direcao_hidraulica": "sim"}
        
    ],
    "valores": [
        {"latitude": -27.590059}, 
        {"longitude": -48.637676},
        {"preco": 600}
    ]

###

# Requisição inválida: falta 'medida'
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "marcadores": [
        {"tipo": "carro1"},
        {"cor": "branco"},
        {"modelo": "hb20"},
        {"arcondicionado": "sim"}
        {"direcao_hidraulica": "sim"}
        
    ],
    "valores": [
        {"latitude": -27.590059}, 
        {"longitude": -48.637676},
        {"preco": 600}
    ]
}

###

# Requisição inválida: 'medida' com formato errado
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "234",
    "marcadores": [
        {"tipo": "carro1"},
        {"cor": "branco"},
        {"modelo": "hb20"},
        {"arcondicionado": "sim"}
        {"direcao_hidraulica": "sim"}
        
    ],
    "valores": [
        {"latitude": -27.590059}, 
        {"longitude": -48.637676},
        {"preco": 600}
    ]
}

###

# Requisição inválida: falta 'valores'
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "arroz123",
    "marcadores": [
        {"tipo": "carro1"},
        {"cor": "branco"},
        {"modelo": "hb20"},
        {"arcondicionado": "sim"}
        {"direcao_hidraulica": "sim"}
        
    ]
}
###

# Requisição inválida: 'valores' com formato errado
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "arroz123",
    "marcadores": [
        {"tipo": "carro1"},
        {"cor": "branco"},
        {"modelo": "hb20"},
        {"arcondicionado": "sim"}
        {"direcao_hidraulica": "sim"}
        
    ],
    "valores": 235
       
}

###

# Requisição inválida: lista 'valores' vazia
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
   "medida": "arroz123",
    "marcadores": [
        {"tipo": "carro1"},
        {"cor": "branco"},
        {"modelo": "hb20"},
        {"arcondicionado": "sim"}
        {"direcao_hidraulica": "sim"}
    ],
    "valores": [
    ]
}

###

# Requisição válida
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "arroz123",
    "marcadores": [
        {"tipo": "carro1"},
        {"cor": "branco"},
        {"modelo": "hb20"},
        {"arcondicionado": "sim"}
        {"direcao_hidraulica": "sim"}
        
    ],
    "valores": [
        {"latitude": -27.590059}, 
        {"longitude": -48.637676},
        {"preco": 600}
    ]
}
###
